package dev.openrune.definition

import dev.openrune.server.definition.NpcServerBase

data class NpcServerType(
    override var id: Int = -1,
    override var name : String = "",
    override var size: Int = 1,
    override var category: Int = -1,
    override var standAnim: Int = -1,
    override var rotateLeftAnim: Int = -1,
    override var rotateRightAnim: Int = -1,
    override var walkAnim: Int = -1,
    override var rotateBackAnim: Int = -1,
    override var walkLeftAnim: Int = -1,
    override var walkRightAnim: Int = -1,
    override var actions: MutableList<String?> = mutableListOf(null, null, null, null, null),
    override var varbit: Int = -1,
    override var varp: Int = -1,
    override var transforms: MutableList<Int>? = null,
    override var combatLevel: Int = -1,
    override var hasRenderPriority: Boolean = false,
    override var lowPriorityFollowerOps: Boolean = false,
    override var isFollower: Boolean = false,
    override var runSequence: Int = -1,
    override var isInteractable : Boolean = true,
    override var runBackSequence: Int = -1,
    override var runRightSequence: Int = -1,
    override var runLeftSequence: Int = -1,
    override var crawlSequence: Int = -1,
    override var crawlBackSequence: Int = -1,
    override var crawlRightSequence: Int = -1,
    override var crawlLeftSequence: Int = -1,
    override var height: Int = -1,
    override var attack : Int = 1,
    override var defence : Int = 1,
    override var strength : Int = 1,
    override var hitpoints : Int = 1,
    override var ranged : Int = 1,
    override var magic : Int = 1,
    override var params: MutableMap<String, Any>? = null,
) : NpcServerBase()