name: Run Git Dumper

on:
  schedule:
    - cron: '0 0 * * 5'  # Every Friday at 00:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  run-git-dumper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run git-dumper with GitHub token
        run: ./gradlew :git-dumper:run --args="${{ secrets.GH_TOKEN }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
